Repository openimsdk/openim-sdk-js-wasm, pull requests merged in 2024-07, with the labels that each got.

#94 feat: release 3.8.0-rc.1
  package.json
  src/api/database/alter.ts
  src/api/database/index.ts
  src/api/database/init.ts
  src/api/index.ts
  src/api/worker.ts
  src/types/index.d.ts
Labels: size/M

#89 fix: typo for enums that should be "normal"
  src/types/enum.ts
Labels: size/S

#98 feat: release 3.8.0-rc.3
  package.json
  src/sdk/index.ts
  src/types/entity.ts
  src/types/index.d.ts
Labels: size/S

#99 feat: release 3.8.0-rc.4
  package.json
  src/sqls/localConversations.ts
Labels: size/XS

#100 fix: OnSyncServerStart & OnSyncServerProgress types
  src/types/eventData.ts
Labels: size/XS

#105 fix: check conversation normal msg seq func
  package.json
  src/api/index.ts
  src/constant/index.ts
  src/types/index.d.ts
Labels: size/XS
